export const GRAY: Record<string, string> = {
  100: '#f5f5f5',
  200: '#e5e5e5',
  300: '#d4d4d4',
  400: '#a3a3a3',
  500: '#737373',
  600: '#525252',
  700: '#404040',
  800: '#262626',
  900: '#171717'
};

export const DAYS_VALUES = [
  'Day.Sunday',
  'Day.Monday',
  'Day.Tuesday',
  'Day.Wednesday',
  'Day.Thursday',
  'Day.Friday',
  'Day.Saturday'
];

export const MONTHS_VALUES = [
  'Month.January',
  'Month.February',
  'Month.March',
  'Month.April',
  'Month.May',
  'Month.June',
  'Month.July',
  'Month.August',
  'Month.September',
  'Month.October',
  'Month.November',
  'Month.December'
];

export const MESSAGES: Record<string, Record<string, string>> = {
  de: {
    'Month.January': 'Januar',
    'Month.February': 'Februar',
    'Month.March': 'Marsch',
    'Month.April': 'April',
    'Month.May': 'Kann',
    'Month.June': 'Juni',
    'Month.July': 'Juli',
    'Month.August': 'August',
    'Month.September': 'September',
    'Month.October': 'Oktober',
    'Month.November': 'November',
    'Month.December': 'Dezember',
    'Day.Sunday': 'Sonntag',
    'Day.Monday': 'Montag',
    'Day.Tuesday': 'Dienstag',
    'Day.Wednesday': 'Mittwoch',
    'Day.Thursday': 'Donnerstag',
    'Day.Friday': 'Freitag',
    'Day.Saturday': 'Samstag',
    'Footer.Today': 'Heute',
    'Footer.Cancel': 'Abbrechen',
    'Footer.Ok': 'Ok'
  },
  en: {
    'Month.January': 'January',
    'Month.February': 'February',
    'Month.March': 'March',
    'Month.April': 'April',
    'Month.May': 'May',
    'Month.June': 'June',
    'Month.July': 'July',
    'Month.August': 'August',
    'Month.September': 'September',
    'Month.October': 'October',
    'Month.November': 'November',
    'Month.December': 'December',
    'Day.Sunday': 'Sunday',
    'Day.Monday': 'Monday',
    'Day.Tuesday': 'Tuesday',
    'Day.Wednesday': 'Wednesday',
    'Day.Thursday': 'Thursday',
    'Day.Friday': 'Friday',
    'Day.Saturday': 'Saturday',
    'Footer.Today': 'Today',
    'Footer.Cancel': 'Cancel',
    'Footer.Ok': 'Ok'
  },
  es: {
    'Month.January': 'Enero',
    'Month.February': 'Febrero',
    'Month.March': 'Marzo',
    'Month.April': 'Abril',
    'Month.May': 'Mayo',
    'Month.June': 'Junio',
    'Month.July': 'Julio',
    'Month.August': 'Agosto',
    'Month.September': 'Septiembre',
    'Month.October': 'Octubre',
    'Month.November': 'Noviembre',
    'Month.December': 'Diciembre',
    'Day.Sunday': 'Domingo',
    'Day.Monday': 'Lunes',
    'Day.Tuesday': 'Martes',
    'Day.Wednesday': 'Miércoles',
    'Day.Thursday': 'Jueves',
    'Day.Friday': 'Viernes',
    'Day.Saturday': 'Sábado',
    'Footer.Today': 'Hoy',
    'Footer.Cancel': 'Anular',
    'Footer.Ok': 'Ok'
  },
  fr: {
    'Month.January': 'Janvier',
    'Month.February': 'Février',
    'Month.March': 'Mars',
    'Month.April': 'Avril',
    'Month.May': 'Mai',
    'Month.June': 'Juin',
    'Month.July': 'Juillet',
    'Month.August': 'Août',
    'Month.September': 'Septembre',
    'Month.October': 'Octobre',
    'Month.November': 'Novembre',
    'Month.December': 'Décembre',
    'Day.Sunday': 'Dimanche',
    'Day.Monday': 'Lundi',
    'Day.Tuesday': 'Mardi',
    'Day.Wednesday': 'Mercredi',
    'Day.Thursday': 'Jeudi',
    'Day.Friday': 'Vendredi',
    'Day.Saturday': 'Samedi',
    'Footer.Today': "Aujourd'hui",
    'Footer.Cancel': 'Annuler',
    'Footer.Ok': 'Ok'
  },
  it: {
    'Month.January': 'Gennaio',
    'Month.February': 'Febbraio',
    'Month.March': 'Marzo',
    'Month.April': 'Aprile',
    'Month.May': 'Maggio',
    'Month.June': 'Giugno',
    'Month.July': 'Luglio',
    'Month.August': 'Agosto',
    'Month.September': 'Settembre',
    'Month.October': 'Ottobre',
    'Month.November': 'Novembre',
    'Month.December': 'Dicembre',
    'Day.Sunday': 'Domenica',
    'Day.Monday': 'Lunedi',
    'Day.Tuesday': 'Martedì',
    'Day.Wednesday': 'Mercoledì',
    'Day.Thursday': 'Giovedì',
    'Day.Friday': 'Venerdì',
    'Day.Saturday': 'Sabato',
    'Footer.Today': 'Oggi',
    'Footer.Cancel': 'Cancellare',
    'Footer.Ok': 'Ok'
  },
  ja: {
    'Month.January': '一月',
    'Month.February': '二月',
    'Month.March': '三月',
    'Month.April': '四月',
    'Month.May': '五月',
    'Month.June': '六月',
    'Month.July': '七月',
    'Month.August': '八月',
    'Month.September': '九月',
    'Month.October': '十月',
    'Month.November': '十一月',
    'Month.December': '十二月',
    'Day.Sunday': '日',
    'Day.Monday': '月',
    'Day.Tuesday': '火',
    'Day.Wednesday': '水',
    'Day.Thursday': '木',
    'Day.Friday': '金',
    'Day.Saturday': '土',
    'Footer.Today': '今',
    'Footer.Cancel': '止める',
    'Footer.Ok': 'Ok'
  }
};
